import type { Metadata } from "next";
// import { getOsuUserData } from "./lib/data";

export const metadata: Metadata = {
  title: "ファンのウェブサイト",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // getOsuUserData();
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
